# Generated by Django 4.1 on 2022-09-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_userreservation_admin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreservation',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
