# Generated by Django 4.1 on 2022-09-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_userreservation_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_address', models.CharField(max_length=200)),
                ('call_us', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('opening', models.CharField(max_length=70)),
                ('map', models.URLField()),
            ],
        ),
    ]
