# Generated by Django 4.1 on 2022-09-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='map',
        ),
    ]
